#!/bin/env zsh

# eza -> ls
alias ls='eza --icons=auto $eza_params'
alias l='eza --icons=auto --git-ignore $eza_params'
alias ll='eza --icons=auto --all --header --long $eza_params'
alias llm='eza --icons=auto --all --header --long --sort=modified $eza_params'
alias la='eza --icons=auto -lbhHigUmuSa'
alias lx='eza --icons=auto -lbhHigUmuSa@'
alias lt='eza --icons=auto --tree $eza_params'
alias tree='eza --icons=auto --tree $eza_params'

# mkdir
alias mkd="mkdir -p"

# emacs
alias edit="emacs -nw"

# git
alias gc="git clone"
alias gcm="git commit -m"
alias gpush="git push"
alias gpull="git pull"

# open (macos-like)
alias open="xdg-open"

# fastfetch
alias ff="fastfetch"

# (r)o(m)ove
alias rmi="rm -ri"
alias rmall="rm -rfi"

# ip addr
alias myIP='curl http://ipecho.net/plain; echo'

# python locale
alias actpy='source ~/.local/python/bin/activate'

# history
alias hh=hstr
