#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vi="nvim" vidf="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	gitUpdate="git push -u origin master"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -a" \
	l="ls -l" \
	ll="ls -la" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="nvim" \
	v="nvim" \
	p="sudo pacman" \
	top="bashtop" \
	Txa="cp ~/Documenti/LaTeX/article.tex" \
	Txbe="cp ~/Documenti/LaTeX/beamer.tex" \
	Txb="cp ~/Documenti/LaTeX/book.tex"


# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \
