# application config

## alacritty
#for_window [app_id="wezterm"] border pixel 2

## telegram desktop
#for_window [app_id="org.telegram.desktop"] border none

## thunderbird
for_window [app_id="thunderbird-default"] border none

## software
for_window [app_id="org.gnome.Software"] border none

## syncthing
for_window [app_id="syncthing-gtk"] border none

# Rende fluttuante qualsiasi finestra con "Meet" nel titolo E che usa l'app_id "chromium".
for_window [app_id="chromium" title="Meet"] floating enable

for_window [app_id="xdg-desktop-portal"] floating enable, border none
for_window [app_id="xdg-desktop-portal-gtk"] floating enable, border none
for_window [app_id="xdg-desktop-portal-kde"] floating enable, border none