# VALORI PER GAPS NORMALI (Default)
set $inner_gaps_normal 5
set $outer_gaps_normal 5

smart_gaps on
gaps inner $inner_gaps_normal
gaps outer $outer_gaps_normal

# VALORI PER GAPS PER VIDEO CENTRATO
set $inner_gaps_video 5
set $outer_gaps_video 100

# Correzione del comando per attivare il layout centrato
bindsym $mod+g exec swaymsg smart_gaps off, gaps inner current set $inner_gaps_video, gaps outer current set $outer_gaps_video

# Correzione del comando per ripristinare il layout normale
bindsym $mod+Shift+g exec swaymsg smart_gaps on, gaps inner current set $inner_gaps_normal, gaps outer current set $outer_gaps_normal