 local menu89b5111c7b2df663bb5b99c457370421 = {
     {"Barrier", "barrier"},
     {"Catarina", "catarina", "/usr/share/icons/hicolor/16x16/apps/catarina.png" },
     {"Gestore di archivi", "file-roller "},
     {"Mark Text", "/usr/lib/marktext/marktext ", "/usr/share/icons/hicolor/16x16/apps/marktext.png" },
     {"Neovim", "xterm -e nvim ", "/usr/share/pixmaps/nvim.png" },
     {"Redshift", "redshift-gtk"},
     {"Screenkey", "screenkey"},
     {"TeX Match", "tex-match"},
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"picom", "picom"},
     {"wpgtk", "/usr/bin/wpg", "/usr/share/pixmaps/wpgtk.png" },
 }

 local menu7c86834f1819f8c0ec3c03ed16470a83 = {
     {"x42-darc", "x42-darc", "/usr/share/icons/hicolor/256x256/apps/x42-darc.png" },
     {"x42-dpl", "x42-dpl", "/usr/share/icons/hicolor/256x256/apps/x42-dpl.png" },
     {"x42-fat1", "x42-fat1", "/usr/share/icons/hicolor/256x256/apps/x42-fat1.png" },
     {"x42-fil4", "x42-fil4"},
     {"x42-matrixmixer8x8", "x42-matrixmixer8x8", "/usr/share/icons/hicolor/256x256/apps/x42-matrixmixer8x8.png" },
     {"x42-meter 1/3 Octave Spectrum Analyzer", "x42-meter 15", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter BBC M-6", "x42-meter 5", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter BBC Meter (Stereo)", "x42-meter 4", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Bit Meter", "x42-meter 18", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter DIN Meter (Stereo)", "x42-meter 6", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter DR-14 - Crest Factor Loudness Range Meter", "x42-meter 11", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter EBU Meter (Stereo)", "x42-meter 7", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter EBU R128 Meter", "x42-meter 0", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Goniometer", "x42-meter 13", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K12/RMS Meter (Stereo)", "x42-meter 3", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K14/RMS Meter (Stereo)", "x42-meter 2", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K20/RMS Meter (Stereo)", "x42-meter 1", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Nordic Meter (Stereo)", "x42-meter 8", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Phase/Frequency Wheel", "x42-meter 14", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Signal Distribution Histogram", "x42-meter 17", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Stereo Phase-Correlation Meter", "x42-meter 12", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Stereo/Frequency Scope", "x42-meter 16", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Surround Level 8", "x42-meter 19", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter True-Peak and RMS Meter (Stereo)", "x42-meter 10", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter VU Meter (Stereo)", "x42-meter 9", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-scope", "x42-scope", "/usr/share/icons/hicolor/256x256/apps/x42-scope.png" },
     {"x42-spectr", "x42-spectr", "/usr/share/icons/hicolor/256x256/apps/x42-spectr.png" },
     {"x42-stepseq", "x42-stepseq", "/usr/share/icons/hicolor/256x256/apps/x42-stepseq.png" },
     {"x42-tuna Instrument Tuner", "x42-tuna 0", "/usr/share/icons/hicolor/256x256/apps/x42-tuna.png" },
     {"x42-tuna Instrument Tuner (Spectrum)", "x42-tuna 1", "/usr/share/icons/hicolor/256x256/apps/x42-tuna.png" },
     {"zamautosat", "ZamAutoSat"},
     {"zamaximx2", "ZaMaximX2"},
     {"zamcomp", "ZamComp"},
     {"zamcompx2", "ZamCompX2"},
     {"zamdelay", "ZamDelay"},
     {"zamdynamiceq", "ZamDynamicEQ"},
     {"zameq2", "ZamEQ2"},
     {"zamgate", "ZamGate"},
     {"zamgatex2", "ZamGateX2"},
     {"zamgeq31", "ZamGEQ31"},
     {"zamheadx2", "ZamHeadX2"},
     {"zammulticompx2", "com.zamaudio.zammulticompx2"},
     {"zamphono", "ZamPhono"},
     {"zamtube", "ZamTube"},
     {"zamulticomp", "ZaMultiComp"},
     {"zamverb", "ZamVerb"},
 }

 local menu2fa9d6ced5c4a03264ae97020096503e = {
     {"3BandEQ", "/usr/bin/3BandEQ"},
     {"3BandSplitter", "/usr/bin/3BandSplitter"},
     {"ADLMIDI", "xterm -e adlrt", "/usr/share/pixmaps/adljack.png" },
     {"ADLMIDI for Jack", "xterm -e adljack", "/usr/share/pixmaps/adljack.png" },
     {"ADLplug", "ADLplug", "/usr/share/icons/hicolor/32x32/apps/ADLplug.png" },
     {"Agordejo", "agordejo", "/usr/share/icons/hicolor/16x16/apps/agordejo.png" },
     {"Agordejo Continue", "agordejo --continue --hide", "/usr/share/icons/hicolor/16x16/apps/agordejo.png" },
     {"AmplitudeImposer", "/usr/bin/AmplitudeImposer"},
     {"Ardour", "ardour6", "/usr/share/icons/hicolor/16x16/apps/ardour6.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cadence", "cadence", "/usr/share/icons/hicolor/16x16/apps/cadence.png" },
     {"Calf Plugin Pack for JACK", "calfjackhost", "/usr/share/icons/hicolor/16x16/apps/calf.png" },
     {"Carla", "carla ", "/usr/share/icons/hicolor/16x16/apps/carla.png" },
     {"Carla Control", "carla-control ", "/usr/share/icons/hicolor/16x16/apps/carla-control.png" },
     {"Catia", "catia", "/usr/share/icons/hicolor/16x16/apps/catia.png" },
     {"CsoundQt", "csoundqt "},
     {"CycleShifter", "/usr/bin/CycleShifter"},
     {"DIN Is Noise", "din", "/usr/share/pixmaps/din.png" },
     {"DragonflyEarlyReflections", "DragonflyEarlyReflections"},
     {"DragonflyHallReverb", "DragonflyHallReverb"},
     {"DragonflyPlateReverb", "DragonflyPlateReverb"},
     {"DragonflyRoomReverb", "DragonflyRoomReverb"},
     {"Drumstick Drum Grid", "drumstick-drumgrid", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick MIDI Player", "drumstick-guiplayer ", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick Virtual Piano", "drumstick-vpiano", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
     {"Element", "element", "/usr/share/icons/hicolor/16x16/apps/net.kushview.element.png" },
     {"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
     {"Fluajho", "fluajho", "/usr/share/icons/hicolor/16x16/apps/fluajho.png" },
     {"FoxDot", "FoxDot", "/usr/share/pixmaps/foxdot.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GTK Youtube Viewer", "gtk-youtube-viewer", "/usr/share/pixmaps/gtk-youtube-viewer.png" },
     {"Geonkick", "env UBUNTU_MENUPROXY=0 geonkick ", "/usr/share/icons/hicolor/16x16/apps/geonkick.png" },
     {"Giada", "giada"},
     {"HDAJackRetask", "hdajackretask"},
     {"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
     {"Helm", "helm-synth", "/usr/share/icons/hicolor/16x16/apps/helm-synth.png" },
     {"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
     {"Hydrogen", "hydrogen "},
     {"JAPA", "japa"},
     {"JSampler Classic", "/usr/bin/jsampler classic", "/usr/share/pixmaps/jsampler-classic.png" },
     {"JSampler Fantasia", "/usr/bin/jsampler fantasia", "/usr/share/pixmaps/jsampler.png" },
     {"Jack Mixer", "jack_mixer", "/usr/share/icons/hicolor/16x16/apps/jack_mixer.png" },
     {"Kars", "/usr/bin/Kars"},
     {"LMMS", "lmms ", "/usr/share/icons/hicolor/16x16/apps/lmms.png" },
     {"Luppp", "luppp", "/usr/share/pixmaps/luppp.png" },
     {"MVerb", "/usr/bin/MVerb"},
     {"MaBitCrush", "/usr/bin/MaBitCrush"},
     {"MaFreeverb", "/usr/bin/MaFreeverb"},
     {"MaGigaverb", "/usr/bin/MaGigaverb"},
     {"MaPitchshift", "/usr/bin/MaPitchshift"},
     {"Mixxx", "sh -c \"pasuspender -- mixxx -platform xcb || mixxx -platform xcb\"", "/usr/share/pixmaps/mixxx_icon.svg" },
     {"MusE", "muse4", "/usr/share/icons/hicolor/64x64/apps/muse.png" },
     {"MuseScore 3.6", "mscore ", "/usr/share/icons/hicolor/16x16/apps/mscore.png" },
     {"Nekobi", "/usr/bin/Nekobi"},
     {"New Session Manager (Legacy GUI)", "nsm-legacy-gui"},
     {"Ninjas2", "ninjas2"},
     {"Non Mixer", "/usr/bin/non-mixer", "/usr/share/icons/hicolor/16x16/apps/non-mixer.png" },
     {"Non Sequencer", "/usr/bin/non-sequencer", "/usr/share/icons/hicolor/16x16/apps/non-sequencer.png" },
     {"Non Timeline", "/usr/bin/non-timeline", "/usr/share/icons/hicolor/16x16/apps/non-timeline.png" },
     {"OBS Studio", "obs", "/usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png" },
     {"OPNplug", "OPNplug", "/usr/share/icons/hicolor/32x32/apps/OPNplug.png" },
     {"PatchMatrix", "/usr/bin/patchmatrix", "/usr/share/icons/hicolor/256x256/apps/patchmatrix.png" },
     {"Patroneo", "patroneo", "/usr/share/icons/hicolor/16x16/apps/patroneo.png" },
     {"PingPongPan", "/usr/bin/PingPongPan"},
     {"Polyphone", "polyphone "},
     {"ProM", "/usr/bin/ProM"},
     {"PulseEffects", "pulseeffects"},
     {"Pure Data", "pd", "/usr/share/icons/hicolor/16x16/apps/pd.png" },
     {"QMidiArp", "qmidiarp "},
     {"QMidiRoute", "qmidiroute"},
     {"QXGEdit", "qxgedit", "/usr/share/icons/hicolor/32x32/apps/qxgedit.png" },
     {"QasConfig", "qasconfig", "/usr/share/icons/hicolor/16x16/apps/qasconfig.png" },
     {"QasHctl", "qashctl", "/usr/share/icons/hicolor/16x16/apps/qashctl.png" },
     {"QasMixer", "qasmixer", "/usr/share/icons/hicolor/16x16/apps/qasmixer.png" },
     {"QjackCtl", "qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"QmidiCtl", "qmidictl"},
     {"QmidiNet", "qmidinet", "/usr/share/icons/hicolor/32x32/apps/qmidinet.png" },
     {"Qsampler", "qsampler ", "/usr/share/icons/hicolor/32x32/apps/qsampler.png" },
     {"Qsynth", "qsynth", "/usr/share/icons/hicolor/32x32/apps/qsynth.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Qtractor", "qtractor ", "/usr/share/icons/hicolor/32x32/apps/qtractor.png" },
     {"Regolazione del volume PulseAudio", "pavucontrol"},
     {"Rosegarden", "rosegarden ", "/usr/share/icons/hicolor/16x16/apps/rosegarden.png" },
     {"Shotcut", "shotcut ", "/usr/share/icons/hicolor/64x64/apps/org.shotcut.Shotcut.png" },
     {"Sonic Pi", "sonic-pi", "/usr/share/pixmaps/sonic-pi.png" },
     {"Sonic Visualiser", "sonic-visualiser "},
     {"SoulForce", "/usr/bin/SoulForce"},
     {"SpectMorph Jack Client", "smjack ", "/usr/share/pixmaps/smjack.png" },
     {"Strawberry", "strawberry ", "/usr/share/icons/hicolor/48x48/apps/strawberry.png" },
     {"SuperCollider IDE", "scide ", "/usr/share/pixmaps/sc_ide.svg" },
     {"Sweep", "sweep", "/usr/share/pixmaps/sweep.svg" },
     {"VMPK", "vmpk", "/usr/share/icons/hicolor/16x16/apps/vmpk.png" },
     {"Vico", "vico", "/usr/share/icons/hicolor/16x16/apps/vico.png" },
     {"Volume Icon", "volumeicon"},
     {"Wolf-spectrum", "wolf-spectrum"},
     {"YASS", "yass"},
     {"Yoshimi", "yoshimi", "/usr/share/pixmaps/yoshimi.png" },
     {"ZynAddSubFX - Alsa", "zynaddsubfx -I alsa -O alsa", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - Jack", "zynaddsubfx -I jack -O jack", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - Jack (multi channel)", "zynaddsubfx -I jack -O jack-multi", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - OSS", "zynaddsubfx -I OSS -O OSS", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"aliki", "aliki"},
     {"ambdec", "ambdec"},
     {"ambix_binaural", "ambix_binaural"},
     {"ambix_converter", "ambix_converter"},
     {"ambix_decoder", "ambix_decoder"},
     {"ambix_directional_loudness", "ambix_directional_loudness"},
     {"ambix_encoder", "ambix_encoder"},
     {"ambix_mirror", "ambix_mirror"},
     {"ambix_rotator", "ambix_rotator"},
     {"ambix_vmic", "ambix_vmic"},
     {"ams", "ams", "/usr/share/pixmaps/ams_32.xpm" },
     {"amsynth", "/usr/bin/amsynth", "/usr/share/icons/hicolor/48x48/apps/amsynth.png" },
     {"drumkv1", "drumkv1_jack", "/usr/share/icons/hicolor/32x32/apps/drumkv1.png" },
     {"ebumeter", "ebumeter"},
     {"gigedit", "gigedit"},
     {"glBars", "/usr/bin/glBars"},
     {"guitarix", "guitarix", "/usr/share/pixmaps/gx_head.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"padthv1", "padthv1_jack", "/usr/share/icons/hicolor/32x32/apps/padthv1.png" },
     {"projectM PulseAudio Visualization", "projectM-pulseaudio"},
     {"samplv1", "samplv1_jack", "/usr/share/icons/hicolor/32x32/apps/samplv1.png" },
     {"setBfree", "setBfreeUI", "/usr/share/pixmaps/setBfree.png" },
     {"snd", "snd"},
     {"ssr", "ssr"},
     {"ssr-aap", "ssr-aap"},
     {"ssr-binaural", "ssr-binaural"},
     {"ssr-brs", "ssr-brs"},
     {"ssr-dca", "ssr-dca"},
     {"ssr-generic", "ssr-generic"},
     {"ssr-vbap", "ssr-vbap"},
     {"ssr-wfs", "ssr-wfs"},
     {"synthv1", "synthv1_jack", "/usr/share/icons/hicolor/32x32/apps/synthv1.png" },
     {"tuxguitar", "tuxguitar", "/usr/share/icons/hicolor/16x16/apps/tuxguitar.png" },
     {"wolf-shaper", "wolf-shaper"},
     {"x42-whirl", "x42-whirl", "/usr/share/pixmaps/x42-whirl.png" },
     {"zamgrains", "ZamGrains"},
     {"zita-at1", "zita-at1"},
     {"zita-bls1", "zita-bls1"},
     {"zita-dc1", "zita-dc1"},
     {"zita-dpl1", "zita-dpl1"},
     {"zita-mu1", "zita-mu1"},
     {"zita-rev1", "zita-rev1"},
 }

 local menu62d9be082af29cffc0e05fa11ab23997 = {
     {"Flameshot", "flameshot", "/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png" },
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"XDvi", "xdvi "},
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"ELinks", "xterm -e /usr/bin/elinks "},
     {"Esploratore Avahi per server SSH", "/usr/bin/bssh"},
     {"Esploratore Avahi per server VNC", "/usr/bin/bvnc"},
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Fondo", "com.github.calo001.fondo", "/usr/share/icons/hicolor/16x16/apps/com.github.calo001.fondo.svg" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Packet Tracer 8.0.0", "/opt/packettracer/packettracer ", "///opt/packettracer/art/app.png" },
     {"Remmina", "remmina-file-wrapper ", "/usr/share/icons/hicolor/16x16/apps/org.remmina.Remmina.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
 }

 local menu202bf2e92c57c0259bea1b2d98ed1c13 = {
     {"Drumstick Drum Grid", "drumstick-drumgrid", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick MIDI Player", "drumstick-guiplayer ", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick Virtual Piano", "drumstick-vpiano", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"GeoGebra", "geogebra"},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"VMPK", "vmpk", "/usr/share/icons/hicolor/16x16/apps/vmpk.png" },
 }

 local menu5464cd25647103af480e2cd7b6db4a0b = {
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron", "electron6 ", "/usr/share/pixmaps/electron6.png" },
     {"Electron 11", "electron11 ", "/usr/share/pixmaps/electron11.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"IntelliJ IDEA Community Edition", "/usr/bin/idea ", "/usr/share/pixmaps/idea.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"SuperCollider IDE", "scide ", "/usr/share/pixmaps/sc_ide.svg" },
 }

 local menud1a552dd2b8819a96dff5a0d73817711 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Esploratore Zeroconf Avahi", "/usr/bin/avahi-discover"},
     {"Fondo", "com.github.calo001.fondo", "/usr/share/icons/hicolor/16x16/apps/com.github.calo001.fondo.svg" },
     {"Gestione stampa", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Gestore file PCManFM", "pcmanfm "},
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 16 Console", "/usr/lib/jvm/java-16-openjdk/bin/jconsole"},
     {"OpenJDK Java 16 Shell", "xterm -e /usr/lib/jvm/java-16-openjdk/bin/jshell"},
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"ranger", "xterm -e ranger"},
 }

 local menud5206603c52c16df2727bec2ec463c3d = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"E-book editor", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"E-book viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"Gummi", "gummi ", "/usr/share/pixmaps/gummi.png" },
     {"Joplin", "/usr/bin/joplin-desktop", "///usr/share/joplin-desktop/resources/build/icons/128x128.png" },
     {"LRF viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Mark Text", "/usr/lib/marktext/marktext ", "/usr/share/icons/hicolor/16x16/apps/marktext.png" },
     {"ProjectLibre", "/usr/bin/projectlibre ", "///usr/share/pixmaps/projectlibre.png" },
     {"Zathura", "zathura ", "/usr/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png" },
     {"x42-mixtri", "x42-mixtri", "/usr/share/icons/hicolor/256x256/apps/x42-mixtri.png" },
 }

xdgmenu = {
    {"Accessori", menu89b5111c7b2df663bb5b99c457370421},
    {"Altro", menu7c86834f1819f8c0ec3c03ed16470a83},
    {"Audio & Video", menu2fa9d6ced5c4a03264ae97020096503e},
    {"Grafica", menu62d9be082af29cffc0e05fa11ab23997},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Istruzione", menu202bf2e92c57c0259bea1b2d98ed1c13},
    {"Programmazione", menu5464cd25647103af480e2cd7b6db4a0b},
    {"Strumenti di sistema", menud1a552dd2b8819a96dff5a0d73817711},
    {"Ufficio", menud5206603c52c16df2727bec2ec463c3d},
}

