 local menu89b5111c7b2df663bb5b99c457370421 = {
     {"Albert", "albert"},
     {"Calcolatrice", "gnome-calculator"},
     {"Conky Manager", "conky-manager ", "/usr/share/pixmaps/conky-manager.png" },
     {"Gestore di archivi", "file-roller "},
     {"Neovim", "xterm -e nvim ", "/usr/share/icons/hicolor/128x128/apps/nvim.png" },
     {"OpenRGB", "openrgb", "/usr/share/icons/hicolor/128x128/apps/OpenRGB.png" },
     {"PDF Slicer", "/usr/bin/pdfslicer "},
     {"Piper", "piper"},
     {"Redshift", "redshift-gtk"},
     {"Screenkey", "screenkey"},
     {"Solaar", "solaar"},
     {"TeX Match", "tex-match", "/usr/share/pixmaps/fyi.zoey.TeX-Match.svg" },
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
 }

 local menu7c86834f1819f8c0ec3c03ed16470a83 = {
     {"zamautosat", "ZamAutoSat"},
     {"zamaximx2", "ZaMaximX2"},
     {"zamcomp", "ZamComp"},
     {"zamcompx2", "ZamCompX2"},
     {"zamdelay", "ZamDelay"},
     {"zamdynamiceq", "ZamDynamicEQ"},
     {"zameq2", "ZamEQ2"},
     {"zamgate", "ZamGate"},
     {"zamgatex2", "ZamGateX2"},
     {"zamgeq31", "ZamGEQ31"},
     {"zamheadx2", "ZamHeadX2"},
     {"zammulticompx2", "com.zamaudio.zammulticompx2"},
     {"zamphono", "ZamPhono"},
     {"zamtube", "ZamTube"},
     {"zamulticomp", "ZaMultiComp"},
     {"zamverb", "ZamVerb"},
 }

 local menu2fa9d6ced5c4a03264ae97020096503e = {
     {"Ardour", "ardour6", "/usr/share/icons/hicolor/16x16/apps/ardour6.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Calf Plugin Pack for JACK", "calfjackhost", "/usr/share/icons/hicolor/16x16/apps/calf.png" },
     {"Carla", "carla ", "/usr/share/icons/hicolor/16x16/apps/carla.png" },
     {"Carla Control", "carla-control ", "/usr/share/icons/hicolor/16x16/apps/carla-control.png" },
     {"Droidcam", "droidcam", "/usr/share/pixmaps/droidcam.png" },
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
     {"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
     {"HDAJackRetask", "hdajackretask"},
     {"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
     {"HandBrake", "ghb "},
     {"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
     {"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
     {"LMMS", "lmms ", "/usr/share/icons/hicolor/16x16/apps/lmms.png" },
     {"Lettore multimediale VLC", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Lollypop", "lollypop ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Lollypop.png" },
     {"OBS Studio", "obs", "/usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png" },
     {"PulseEffects", "pulseeffects"},
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Regolazione del volume PulseAudio", "pavucontrol"},
     {"Shortwave", "shortwave"},
     {"Shotcut", "shotcut ", "/usr/share/icons/hicolor/64x64/apps/org.shotcut.Shotcut.png" },
     {"Sonic Visualiser", "sonic-visualiser "},
     {"Sound Converter", "soundconverter ", "/usr/share/pixmaps/soundconverter.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"projectM PulseAudio Visualization", "projectM-pulseaudio"},
     {"zamgrains", "ZamGrains"},
 }

 local menu5598904a204cc436e5c652f27673b58e = {
     {"Lutris", "lutris ", "/usr/share/icons/hicolor/16x16/apps/lutris.png" },
     {"OpenArena", "openarena", "/usr/share/pixmaps/openarena.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
 }

 local menu62d9be082af29cffc0e05fa11ab23997 = {
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"Flameshot", "/usr/bin/flameshot", "/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png" },
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"XDvi", "xdvi "},
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Apri nel dispositivo connesso tramite KDE Connect", "kdeconnect-handler --open "},
     {"Brave", "brave ", "/usr/share/icons/hicolor/16x16/apps/brave-desktop.png" },
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"Esploratore Avahi per server SSH", "/usr/bin/bssh"},
     {"Esploratore Avahi per server VNC", "/usr/bin/bvnc"},
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Fondo", "com.github.calo001.fondo", "/usr/share/icons/hicolor/16x16/apps/com.github.calo001.fondo.svg" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Indicatore di KDE Connect", "kdeconnect-indicator"},
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect SMS", "kdeconnect-sms"},
     {"Microsoft Teams - Preview", "teams ", "/usr/share/pixmaps/teams.png" },
     {"OpenArena Server", "xterm -e openarena-server", "/usr/share/pixmaps/openarena-server.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Thunderbird", "/usr/lib/thunderbird/thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Visualizzatore remoto", "remote-viewer ", "/usr/share/icons/hicolor/16x16/apps/virt-viewer.png" },
     {"Xpra", "xpra", "/usr/share/icons/xpra.png" },
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
     {"whatsdesk", "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/whatsdesk_whatsdesk.desktop /var/lib/snapd/snap/bin/whatsdesk ", "///var/lib/snapd/snap/whatsdesk/28/meta/gui/icon.png" },
 }

 local menu202bf2e92c57c0259bea1b2d98ed1c13 = {
     {"GNU Octave", "/usr/bin/octave --gui ", "/usr/share/icons/hicolor/16x16/apps/octave.png" },
     {"GeoGebra", "geogebra"},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu5464cd25647103af480e2cd7b6db4a0b = {
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Code - OSS", "/usr/bin/code-oss --unity-launch ", "/usr/share/pixmaps/com.visualstudio.code.oss.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron 13", "electron13 ", "/usr/share/pixmaps/electron13.png" },
     {"Electron 14", "electron14 ", "/usr/share/pixmaps/electron14.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"GitHub Desktop", "/usr/bin/github-desktop ", "/usr/share/icons/hicolor/256x256/apps/github-desktop.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDBusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
 }

 local menud1a552dd2b8819a96dff5a0d73817711 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Esploratore Zeroconf Avahi", "/usr/bin/avahi-discover"},
     {"Fondo", "com.github.calo001.fondo", "/usr/share/icons/hicolor/16x16/apps/com.github.calo001.fondo.svg" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Gestione stampa", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Il gestore dei file Thunar", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"OpenJDK Java 17 Console", "/usr/lib/jvm/java-17-openjdk/bin/jconsole"},
     {"OpenJDK Java 17 Shell", "xterm -e /usr/lib/jvm/java-17-openjdk/bin/jshell"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Rinomina di massa", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Snap Store", "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/snap-store_snap-store.desktop /var/lib/snapd/snap/bin/snap-store ", "///var/lib/snapd/snap/snap-store/558/meta/gui/io.snapcraft.Store.png" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"conky", "conky --daemonize --pause=1"},
     {"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
     {"ranger", "xterm -e ranger"},
 }

 local menud5206603c52c16df2727bec2ec463c3d = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"E-book editor", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"E-book viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LRF viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"ONLYOFFICE Desktop Editors", "/usr/bin/onlyoffice-desktopeditors ", "/usr/share/icons/hicolor/16x16/apps/onlyoffice-desktopeditors.png" },
     {"PDF Slicer", "/usr/bin/pdfslicer "},
     {"Sweet Home 3D", "sweethome3d ", "/usr/share/pixmaps/sweethome3d.png" },
     {"TeXstudio", "texstudio ", "/usr/share/icons/hicolor/16x16/apps/texstudio.png" },
     {"Xournal++", "xournalpp "},
     {"Zathura", "zathura ", "/usr/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png" },
 }

xdgmenu = {
    {"Accessori", menu89b5111c7b2df663bb5b99c457370421},
    {"Altro", menu7c86834f1819f8c0ec3c03ed16470a83},
    {"Audio & Video", menu2fa9d6ced5c4a03264ae97020096503e},
    {"Giochi", menu5598904a204cc436e5c652f27673b58e},
    {"Grafica", menu62d9be082af29cffc0e05fa11ab23997},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Istruzione", menu202bf2e92c57c0259bea1b2d98ed1c13},
    {"Programmazione", menu5464cd25647103af480e2cd7b6db4a0b},
    {"Strumenti di sistema", menud1a552dd2b8819a96dff5a0d73817711},
    {"Ufficio", menud5206603c52c16df2727bec2ec463c3d},
}

